services:
  - type: web
    name: jamii-loan-backend
    env: node
    region: singapore
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: development
      - key: PORT
        value: 5000
      - key: MONGO_URI
        fromSecret: mongodb+srv://Mathew:Mat2018@quickloan.ownvxer.mongodb.net/?retryWrites=true&w=majority&appName=QUICKLOAN
      - key: JWT_SECRET
        fromSecret: qawsedrftgyhujikolp
      - key: EMAIL_USER
        fromSecret: kiokomathew1985@gmail.com
      - key: EMAIL_PASS
        fromSecret: gmugaohtzrktcjjz
      - key: FLUTTERWAVE_PUBLIC_KEY
        fromSecret: flutterwave_public_key
      - key: FLUTTERWAVE_SECRET_KEY
        fromSecret: flutterwave_secret_key
      - key: FRONTEND_URL
        value: https://jamii-loan.netlify.app
